### ISSUE TITLE
(PYL-R1720) Unnecessary `else`/`elif` used after `raise`

### ISSUE THREAD

**Issue by harisonmg** [harisonmg/church-ims#81]
## Description
`raise` causes control flow to be disrupted, as it will exit the block. It is recommended to check other conditions using another `if` statement, and get rid of `else` statements as they are unnecessary.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/harisonmg/church-ims/issue/PYL-R1720/occurrences/](https://deepsource.io/gh/harisonmg/church-ims/issue/PYL-R1720/occurrences/)

**Comment by SNFernandes24** [comment]
```
else:
        raise ValueError(MAX_HUMAN_AGE_EXCEEDED_ERROR)
```
Should be removed or updated with an if statement to check if above a certain age?

**Comment by harisonmg** [comment]
> ```
> else:
>         raise ValueError(MAX_HUMAN_AGE_EXCEEDED_ERROR)
> ```
> 
> Should be removed or updated with an if statement to check if above a certain age?

Yes. It should be updated to `if` to preserve the error handling

**Comment by SNFernandes24** [comment]
Harisonmg, I tried to do a pull request but ran into some style guideline problems. First, one is for all the elif statements as it prefers them to be if statement if it is after a return.

```
def get_age_category(age):
    if age < CHILD[0]:
        raise ValueError(NEGATIVE_AGE_ERROR)
    if age < TEENAGER[0]:
        return "child"
    if age < YOUNG_ADULT[0]:
        return "teenager"
    if age < ADULT[0]:
        return "young adult"
    if age < MIDDLE_AGED[0]:
        return "adult"
    if age < SENIOR_CITIZEN[0]:
        return "middle-aged"
    if age <= SENIOR_CITIZEN[1]:
        return "senior citizen"
    if age > SENIOR_CITIZEN[1]:
        raise ValueError(MAX_HUMAN_AGE_EXCEEDED_ERROR)
```

That seems to get past the first style guide, but the second one requires return statement for all as noted here:

```
Either all return statements in a function should return an expression, or none of them should.
```

Let me know if you want me to make any further changes to the above functions to reflect style guidelines.

**Comment by harisonmg** [comment]
> Harisonmg, I tried to do a pull request but ran into some style guideline problems. First, one is for all the elif statements as it prefers them to be if statement if it is after a return.
> 
> ```
> def get_age_category(age):
>     if age < CHILD[0]:
>         raise ValueError(NEGATIVE_AGE_ERROR)
>     if age < TEENAGER[0]:
>         return "child"
>     if age < YOUNG_ADULT[0]:
>         return "teenager"
>     if age < ADULT[0]:
>         return "young adult"
>     if age < MIDDLE_AGED[0]:
>         return "adult"
>     if age < SENIOR_CITIZEN[0]:
>         return "middle-aged"
>     if age <= SENIOR_CITIZEN[1]:
>         return "senior citizen"
>     if age > SENIOR_CITIZEN[1]:
>         raise ValueError(MAX_HUMAN_AGE_EXCEEDED_ERROR)
> ```
> 
> That seems to get past the first style guide, but the second one requires return statement for all as noted here:
> 
> ```
> Either all return statements in a function should return an expression, or none of them should.
> ```
> 
> Let me know if you want me to make any further changes to the above functions to reflect style guidelines.

Here is a clue:  keep like "terms" together. The error handling statements should be at the top, followed by `if`/`elif` statements that have return values. To fully resolve the issue, store the values in a variable like `age_category` and return the variable after the last `else`/`elif`. 

Thanks for the effort.
